site_name: ValidationHelper
repo_url: https://github.com/yamagh/validationhelper
theme:
  name: material
  palette:
    primary: white
    accent: pink
  logo: img/icon.svg
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: overrides
  gtags:
    - G-0BSW43D88H
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    # - header.autohide
    # - toc.integrate
markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting started:
    - Installation: Getting-started/Installation.md
    - Tutorial: Getting-started/Tutorial.md
  - Reference:
    - Actions: Reference/actions.md
    - Validation Types: Reference/validation-types.md
    - Element: Reference/Element.md
    - Existence: Reference/Existence.md
    - Format: Reference/Format.md
    - Length: Reference/Length.md
    - Numecarity: Reference/Numecarity.md
    - Uniqueness: Reference/Uniqueness.md
  - Reading material:
    - Why need this: Reading-material/why-need-this.md
  - Contribution: Contribution/contribution.md