site_name: ValidationHelper
repo_url: https://github.com/yamagh/validationhelper
theme:
  name: material
  palette:
    primary: white
    accent: pink
  logo: img/icon.svg
  icon:
    repo: fontawesome/brands/git-alt
  gtags:
    - G-0BSW43D88H
nav:
  - Top: index.md
  - Tutorial: Tutorial.md
  - Reference: Reference.md
