site_name: ValidationHelper
repo_url: https://github.com/yamagh/validationhelper
theme:
  name: material
  palette:
    primary: white
    accent: pink
  logo: img/icon.svg
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: overrides
  gtags:
    - G-0BSW43D88H
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.indexes
    # - toc.integrate
markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - toc:
      permalink: true